# Generated by Django 4.0.1 on 2022-02-08 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_availabledates_created_at_availabledates_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='expiry',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availabledates',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='events.events'),
        ),
    ]
