# Generated by Django 4.0.1 on 2022-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_expiry_alter_availabledates_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledates',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availabledates',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
