# Generated by Django 4.0.1 on 2022-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_availabledates_end_alter_availabledates_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='pending',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='selected_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
