# Generated by Django 4.0.1 on 2022-02-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_expiry_alter_events_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
