# Generated by Django 4.0.3 on 2022-03-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_events_invitee_alter_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='selected_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
