version: '1.0'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}
services:
    ### PostgreSQL ###########################################
    postgres:
      build:
        context: ./infrastructure/postgres
        args:
          - POSTGRES_VERSION=${POSTGRES_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
        - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - MEETSY_POSTGRES_DB=${MEETSY_POSTGRES_DB}
        - MEETSY_POSTGRES_USER=${MEETSY_POSTGRES_USER}
        - MEETSY_POSTGRES_PASSWORD=${MEETSY_POSTGRES_PASSWORD}
      networks:
        - backend

    ### Meetsy Backend ###########################################
    core:
      build:
        context: ./
        dockerfile: './infrastructure/app/Dockerfile'
      ports:
        - "8000:8000"
      networks:
        - backend